feat: use deployment image and config map

diff --git a/src/kubectl-application-shell b/src/kubectl-application-shell
--- a/src/kubectl-application-shell
+++ b/src/kubectl-application-shell
@@ -5,6 +5,18 @@
 
 #!/bin/bash
 
+while [ -n "$1" ]; do # while loop starts
+	case "$1" in
+	--namespace) namespace=$2 && echo "namespace = $namespace" ;;
+  --name) name=$2 && echo "name = $name" ;;
+	--image) image=$2 && echo "image = $image" ;;
+	--config) config=$2 && echo "config = $config" ;;
+	--*) echo "Option $1 not recognized" ;;
+
+	esac
+	shift
+done
+
 # optional argument handling
 if [[ "$1" == "version" ]]
 then
@@ -12,54 +24,60 @@ then
     exit 0
 fi
 
-if [[ "$1" == "" ]]
+if [[ "$name" == "" ]]
 then
     echo "Missing name."
     exit 1
 fi
 
-if [[ ! "$2" =~ ":" ]]
+if [[ "$namespace" == "" ]]
 then
-    echo "Missing explicit image tag."
+    echo "Missing namespace."
     exit 1
 fi
 
-if [[ "$2" == "" ]]
+if [[ "$image" == "" ]]
 then
     echo "Missing image. Using currently deployed image from the deployment name."
-else
-    deploymentname=$2
+    image=`kubectl get deployment --namespace=$namespace $name -o=jsonpath='{$.spec.template.spec.containers[:1].image}'`
 fi
 
-if [[ "$3" == "" ]]
+if [[ ! "$image" =~ ":" ]]
+then
+    if [[ $image == "" ]]
+    then
+        echo "Missing explicit image tag."
+        exit 1
+    fi
+fi
+
+if [[ "$config" == "" ]]
 then
     echo "Missing config map. Using currently deployed config-map from the deployment name."
-else
-    configmapname=$3
+    config=`kubectl get deployment --namespace=$namespace $name -o=jsonpath='{$.spec.template.spec.containers[:1].envFrom[0].configMapRef.name}'`
 fi
 
-deploymentname=`kubectl get deployment $1 -o=jsonpath='{$.spec.template.spec.containers[:1].image}'`
-configmapname=`kubectl get deployment $1 -o=jsonpath='{$.spec.template.spec.containers[:1].envFrom[0].configMapRef.name}'`
-
-kubectl run -it --rm $1 --image=$2 --restart=Never --overrides='
+overrides="
 {
-  "spec": {
-    "containers": [
+  \"spec\": {
+    \"containers\": [
       {
-        "name": $1,
-        "image": $deploymentname,
-        "args": ["/bin/bash"],
-        "envFrom": [
+        \"name\": $name,
+        \"image\": $image,
+        \"args\": [\"/bin/bash\"],
+        \"envFrom\": [
           {
-            "configMapRef": {
-              "name": $configmapname
+            \"configMapRef\": {
+              \"name\": $config
             }
           }
         ],
-        "stdin": true,
-        "stdinOnce": true,
-        "tty": true
+        \"stdin\": true,
+        \"stdinOnce\": true,
+        \"tty\": true
       }
     ]
   }
-}'
+}"
+
+kubectl run -it --rm --namespace=$namespace $name --image=$image --restart=Never --overrides=$overrides
